//"C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\xsd.exe" "C:\SVN\Resnet\branches\2016.06.07.NewPnyMcBPO\Resnet\WebService\ReoServices\FNC_IF\SendCMSOrders\srce\FormInfoResponse.xsd" /c /f /namespace:ResNet.Bpo.CMS /out:"C:\SVN\Resnet\branches\2016.06.07.NewPnyMcBPO\Resnet\WebService\ReoServices\FNC_IF\SendCMSOrders\srce"
//
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ResNet.Bpo.CMS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RESPONSE {
        
        /// <remarks/>
        public RESPONSECONFIRMATION CONFIRMATION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public RESPONSEURL[] URL;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RESPONSECONFIRMATION {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SUCCESS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string REASON;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RESPONSEURL {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
}
