//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace ResNet.Bpo.CMS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FORMINFO {
        
        /// <remarks/>
        public FORMINFOSUBJECT SUBJECT;
        
        /// <remarks/>
        public FORMINFOREVIEW REVIEW;
        
        /// <remarks/>
        public FORMINFOLENDERCLIENT LENDERCLIENT;
        
        /// <remarks/>
        public FORMINFOIMPROVEMENTS IMPROVEMENTS;
        
        /// <remarks/>
        public FORMINFOLISTINGCOMP LISTINGCOMP;
        
        /// <remarks/>
        public FORMINFOSITE SITE;
        
        /// <remarks/>
        public FORMINFOLISTBROKER LISTBROKER;
        
        /// <remarks/>
        public FORMINFOREPORT REPORT;
        
        /// <remarks/>
        public FORMINFONBRHOOD NBRHOOD;
        
        /// <remarks/>
        public FORMINFOCOMMENT COMMENT;
        
        /// <remarks/>
        public FORMINFOSALESCOMP SALESCOMP;
        
        /// <remarks/>
        public FORMINFORECONCIL RECONCIL;
        
        /// <remarks/>
        public FORMINFOADDENDUMS ADDENDUMS;
        
        /// <remarks/>
        public FORMINFOBROKER BROKER;
        
        /// <remarks/>
        public FORMINFOAPPRAISER APPRAISER;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FORMNUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FILENUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VENDOR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VERSION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CASE_NO;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DOCID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FORMVERSION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSUBJECT {
        
        /// <remarks/>
        public FORMINFOSUBJECTADDR ADDR;
        
        /// <remarks/>
        public FORMINFOSUBJECTASSESPARCEL ASSESPARCEL;
        
        /// <remarks/>
        public string LOANNUM;
        
        /// <remarks/>
        public FORMINFOSUBJECTORDER ORDER;
        
        /// <remarks/>
        public FORMINFOSUBJECTTRACKING TRACKING;
        
        /// <remarks/>
        public string BORROWER;
        
        /// <remarks/>
        public string CURRENTOWNER;
        
        /// <remarks/>
        public string COUNTY;
        
        /// <remarks/>
        public FORMINFOSUBJECTPROJ PROJ;
        
        /// <remarks/>
        public string HOMEOWNERASSNFEE;
        
        /// <remarks/>
        public FORMINFOSUBJECTDISASTER DISASTER;
        
        /// <remarks/>
        public FORMINFOSUBJECTSOLDLISTED SOLDLISTED;
        
        /// <remarks/>
        public string CURRENTOCCUPANT;
        
        /// <remarks/>
        public string PROPSECURE;
        
        /// <remarks/>
        public string CURRENTUSE;
        
        /// <remarks/>
        public string PROJECTEDUSE;
        
        /// <remarks/>
        public string DATASRC;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSUBJECTADDR {
        
        /// <remarks/>
        public string STREET;
        
        /// <remarks/>
        public string CITY;
        
        /// <remarks/>
        public string STATEPROV;
        
        /// <remarks/>
        public string ZIP;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSUBJECTASSESPARCEL {
        
        /// <remarks/>
        public string NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSUBJECTORDER {
        
        /// <remarks/>
        public string NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSUBJECTTRACKING {
        
        /// <remarks/>
        public string NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSUBJECTPROJ {
        
        /// <remarks/>
        public string TYPE;
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSUBJECTDISASTER {
        
        /// <remarks/>
        public string RESPONSE;
        
        /// <remarks/>
        public string DATE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSUBJECTSOLDLISTED {
        
        /// <remarks/>
        public string PREVIOUSPRICE;
        
        /// <remarks/>
        public string PREVIOUSDATE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VALUE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEW {
        
        /// <remarks/>
        public string DESCRIPTION;
        
        /// <remarks/>
        public string TYPE;
        
        /// <remarks/>
        public FORMINFOREVIEWREPORTSECTION REPORTSECTION;
        
        /// <remarks/>
        public FORMINFOREVIEWMARKETDATA MARKETDATA;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWREPORTSECTION {
        
        /// <remarks/>
        public FORMINFOREVIEWREPORTSECTIONSUBJECT SUBJECT;
        
        /// <remarks/>
        public FORMINFOREVIEWREPORTSECTIONNBRHOOD NBRHOOD;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWREPORTSECTIONSUBJECT {
        
        /// <remarks/>
        public string COMMENTS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWREPORTSECTIONNBRHOOD {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWMARKETDATA {
        
        /// <remarks/>
        public FORMINFOREVIEWMARKETDATASUBJECT SUBJECT;
        
        /// <remarks/>
        public FORMINFOREVIEWMARKETDATACOMPAGE COMPAGE;
        
        /// <remarks/>
        public FORMINFOREVIEWMARKETDATASOLD6MONTHS SOLD6MONTHS;
        
        /// <remarks/>
        public FORMINFOREVIEWMARKETDATASOLD3MONTHS SOLD3MONTHS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWMARKETDATASUBJECT {
        
        /// <remarks/>
        public string LIVINGSQFT;
        
        /// <remarks/>
        public string LOTSIZE;
        
        /// <remarks/>
        public FORMINFOREVIEWMARKETDATASUBJECTABOVEGRADE ABOVEGRADE;
        
        /// <remarks/>
        public string NUMUNITS;
        
        /// <remarks/>
        public string PROPTYPE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWMARKETDATASUBJECTABOVEGRADE {
        
        /// <remarks/>
        public string BEDROOMS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWMARKETDATACOMPAGE {
        
        /// <remarks/>
        public string RESPONSE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWMARKETDATASOLD6MONTHS {
        
        /// <remarks/>
        public string LISTPRICEAVG;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREVIEWMARKETDATASOLD3MONTHS {
        
        /// <remarks/>
        public string LISTPRICEAVG;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLENDERCLIENT {
        
        /// <remarks/>
        public FORMINFOLENDERCLIENTCOMPANY COMPANY;
        
        /// <remarks/>
        public FORMINFOLENDERCLIENTADDR ADDR;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLENDERCLIENTCOMPANY {
        
        /// <remarks/>
        public string NAME;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLENDERCLIENTADDR {
        
        /// <remarks/>
        public string STREET;
        
        /// <remarks/>
        public string CITY;
        
        /// <remarks/>
        public string STATEPROV;
        
        /// <remarks/>
        public string ZIP;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOIMPROVEMENTS {
        
        /// <remarks/>
        public FORMINFOIMPROVEMENTSGENERAL GENERAL;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOIMPROVEMENTSGENERAL {
        
        /// <remarks/>
        public string NEWCONSTRUCTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMP {
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPSUBJECT SUBJECT;
        
        /// <remarks/>
        public string NUM;
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPPRICE PRICE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("REPAIR")]
        public FORMINFOLISTINGCOMPREPAIR[] REPAIR;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LISTCOMPS")]
        public FORMINFOLISTINGCOMPLISTCOMPS[] LISTCOMPS;
        
        /// <remarks/>
        public string ANALYSISLISTINGDATA;
        
        /// <remarks/>
        public string ANALYSISLISTINGDATA2;
        
        /// <remarks/>
        public string ANALYSISLISTINGDATA3;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPSUBJECT {
        
        /// <remarks/>
        public string MARKETDAYS;
        
        /// <remarks/>
        public string ORIGINALPRICE;
        
        /// <remarks/>
        public string ORIGINALLISTINGDATE;
        
        /// <remarks/>
        public string LISTINGPRICE;
        
        /// <remarks/>
        public string REVISIONDATE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPPRICE {
        
        /// <remarks/>
        public string LOW;
        
        /// <remarks/>
        public string HIGH;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPREPAIR {
        
        /// <remarks/>
        public string ITEM;
        
        /// <remarks/>
        public string RESPONSE;
        
        /// <remarks/>
        public string ESTCOST;
        
        /// <remarks/>
        public string TOTALCOST;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPLISTCOMPS {
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPLISTCOMPSADDR ADDR;
        
        /// <remarks/>
        public string DATA;
        
        /// <remarks/>
        public string PROXIMITY;
        
        /// <remarks/>
        public string ORGLISTINGDT;
        
        /// <remarks/>
        public string ORIGINALPRICE;
        
        /// <remarks/>
        public string LISTINGPRICE;
        
        /// <remarks/>
        public string MARKETDAYS;
        
        /// <remarks/>
        public string TOTDAYSMARKET;
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPLISTCOMPSSRCFUNDS SRCFUNDS;
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPLISTCOMPSCONCESSIONS CONCESSIONS;
        
        /// <remarks/>
        public string DISTRESSEDSALE;
        
        /// <remarks/>
        public string LOTSIZE;
        
        /// <remarks/>
        public string SITE;
        
        /// <remarks/>
        public string VIEW;
        
        /// <remarks/>
        public string VIEWCOMPARISON;
        
        /// <remarks/>
        public string PROPTYPE;
        
        /// <remarks/>
        public string UNITNUM;
        
        /// <remarks/>
        public string CONSTRUCT;
        
        /// <remarks/>
        public string DESIGNSTYLE;
        
        /// <remarks/>
        public string AGEYRS;
        
        /// <remarks/>
        public string CONDITION;
        
        /// <remarks/>
        public string LIVINGSQFT;
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPLISTCOMPSABOVEGRADE ABOVEGRADE;
        
        /// <remarks/>
        public string BASEMENTTYPE;
        
        /// <remarks/>
        public string BASEMENT;
        
        /// <remarks/>
        public string BASEMENTFINISH;
        
        /// <remarks/>
        public string GARAGE;
        
        /// <remarks/>
        public string GARAGENUMCARS;
        
        /// <remarks/>
        public string POOL;
        
        /// <remarks/>
        public string OTHERAMENITIES;
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPLISTCOMPSHOAASSESSMENT HOAASSESSMENT;
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPLISTCOMPSMOSTCOMPARABLE MOSTCOMPARABLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte COMPNUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPLISTCOMPSADDR {
        
        /// <remarks/>
        public string STREET;
        
        /// <remarks/>
        public string CITY;
        
        /// <remarks/>
        public string ZIP;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPLISTCOMPSSRCFUNDS {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPLISTCOMPSCONCESSIONS {
        
        /// <remarks/>
        public FORMINFOLISTINGCOMPLISTCOMPSCONCESSIONSSALES SALES;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPLISTCOMPSCONCESSIONSSALES {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPLISTCOMPSABOVEGRADE {
        
        /// <remarks/>
        public string ROOMTOT;
        
        /// <remarks/>
        public string BEDROOMS;
        
        /// <remarks/>
        public string BATHFULL;
        
        /// <remarks/>
        public string BATHHALF;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPLISTCOMPSHOAASSESSMENT {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTINGCOMPLISTCOMPSMOSTCOMPARABLE {
        
        /// <remarks/>
        public string RESPONSE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSITE {
        
        /// <remarks/>
        public FORMINFOSITESALESHISTORY SALESHISTORY;
        
        /// <remarks/>
        public FORMINFOSITEZONING ZONING;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSITESALESHISTORY {
        
        /// <remarks/>
        public string RESPONSE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSITEZONING {
        
        /// <remarks/>
        public string SPECIFIC;
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTBROKER {
        
        /// <remarks/>
        public string NAME;
        
        /// <remarks/>
        public FORMINFOLISTBROKERCOMPANY COMPANY;
        
        /// <remarks/>
        public string PHONE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOLISTBROKERCOMPANY {
        
        /// <remarks/>
        public string NAME;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOREPORT {
        
        /// <remarks/>
        public string DATE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOOD {
        
        /// <remarks/>
        public string LOCATION;
        
        /// <remarks/>
        public string PROPVALUES;
        
        /// <remarks/>
        public string MARKETINGTIME;
        
        /// <remarks/>
        public FORMINFONBRHOODHOUSINGSUMMARY HOUSINGSUMMARY;
        
        /// <remarks/>
        public string MARKETINGTIMEDESCRIPTION;
        
        /// <remarks/>
        public FORMINFONBRHOODOCCUPANCY OCCUPANCY;
        
        /// <remarks/>
        public FORMINFONBRHOODLANDUSE LANDUSE;
        
        /// <remarks/>
        public string NEWCONSTRUCTION;
        
        /// <remarks/>
        public FORMINFONBRHOODDISASTER DISASTER;
        
        /// <remarks/>
        public string MARKETCONDITIONS;
        
        /// <remarks/>
        public FORMINFONBRHOODCLOSEDSALESPAST CLOSEDSALESPAST;
        
        /// <remarks/>
        public FORMINFONBRHOODMARKET MARKET;
        
        /// <remarks/>
        public FORMINFONBRHOODPENDINGSALES PENDINGSALES;
        
        /// <remarks/>
        public string DEMANDSUPPLY;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODHOUSINGSUMMARY {
        
        /// <remarks/>
        public string MEDIANRENT;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODOCCUPANCY {
        
        /// <remarks/>
        public FORMINFONBRHOODOCCUPANCYOWNER OWNER;
        
        /// <remarks/>
        public FORMINFONBRHOODOCCUPANCYVACANT VACANT;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODOCCUPANCYOWNER {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OWNER;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODOCCUPANCYVACANT {
        
        /// <remarks/>
        public string PERCENT;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODLANDUSE {
        
        /// <remarks/>
        public string INDUSTRIAL;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODDISASTER {
        
        /// <remarks/>
        public string RESPONSE;
        
        /// <remarks/>
        public string DATE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODCLOSEDSALESPAST {
        
        /// <remarks/>
        public string NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODMARKET {
        
        /// <remarks/>
        public FORMINFONBRHOODMARKETABSORPTIONRATE ABSORPTIONRATE;
        
        /// <remarks/>
        public FORMINFONBRHOODMARKETMEDIANSALESPRICE MEDIANSALESPRICE;
        
        /// <remarks/>
        public FORMINFONBRHOODMARKETSALESTOLISTRATIO SALESTOLISTRATIO;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODMARKETABSORPTIONRATE {
        
        /// <remarks/>
        public string LAST4TO6MOS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODMARKETMEDIANSALESPRICE {
        
        /// <remarks/>
        public string LAST4TO6MOS;
        
        /// <remarks/>
        public string LAST3MONTHS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODMARKETSALESTOLISTRATIO {
        
        /// <remarks/>
        public string LAST4TO6MOS;
        
        /// <remarks/>
        public string LAST3MONTHS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFONBRHOODPENDINGSALES {
        
        /// <remarks/>
        public string NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOCOMMENT {
        
        /// <remarks/>
        public string REOSALESEFFECT;
        
        /// <remarks/>
        public string COMMENTS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMP {
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSALES COMPSALES;
        
        /// <remarks/>
        public FORMINFOSALESCOMPSUBJECT SUBJECT;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COMPS")]
        public FORMINFOSALESCOMPCOMPS[] COMPS;
        
        /// <remarks/>
        public string COMMENTSALE1;
        
        /// <remarks/>
        public string COMMENTSALE2;
        
        /// <remarks/>
        public string COMMENTSALE3;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSALES {
        
        /// <remarks/>
        public string NUM;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSALESPRICE PRICE;
        
        /// <remarks/>
        public string RADIUS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSALESPRICE {
        
        /// <remarks/>
        public string LOW;
        
        /// <remarks/>
        public string HIGH;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPSUBJECT {
        
        /// <remarks/>
        public string YRBUILT;
        
        /// <remarks/>
        public FORMINFOSALESCOMPSUBJECTABOVEGRADE ABOVEGRADE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPSUBJECTADDR ADDR;
        
        /// <remarks/>
        public string ORIGINALLISTDT;
        
        /// <remarks/>
        public string ORIGINALLISTPRICE;
        
        /// <remarks/>
        public string CURRENTLISTPRICE;
        
        /// <remarks/>
        public string DAYSONMARKET;
        
        /// <remarks/>
        public string TOTDAYSONMARKET;
        
        /// <remarks/>
        public string SRCFUNDS;
        
        /// <remarks/>
        public FORMINFOSALESCOMPSUBJECTCONCESSIONS CONCESSIONS;
        
        /// <remarks/>
        public string DISTRESSEDSALE;
        
        /// <remarks/>
        public string LOTSIZE;
        
        /// <remarks/>
        public string SITE;
        
        /// <remarks/>
        public string VIEW;
        
        /// <remarks/>
        public string PROPTYPE;
        
        /// <remarks/>
        public string NUMUNITS;
        
        /// <remarks/>
        public string CONSTRUCT;
        
        /// <remarks/>
        public string DESIGNSTYLE;
        
        /// <remarks/>
        public string AGEYRS;
        
        /// <remarks/>
        public string CONDITION;
        
        /// <remarks/>
        public string LIVINGSQFT;
        
        /// <remarks/>
        public string BASEMENTTYPE;
        
        /// <remarks/>
        public string BASEMENT;
        
        /// <remarks/>
        public string BASEMENTFINISH;
        
        /// <remarks/>
        public string GARAGE;
        
        /// <remarks/>
        public string GARAGENUMCARS;
        
        /// <remarks/>
        public string POOL;
        
        /// <remarks/>
        public string AMENITIES;
        
        /// <remarks/>
        public string HOAASSESSMENT;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPSUBJECTABOVEGRADE {
        
        /// <remarks/>
        public string BATH;
        
        /// <remarks/>
        public string ROOMTOT;
        
        /// <remarks/>
        public string BEDROOMS;
        
        /// <remarks/>
        public string BATHFULL;
        
        /// <remarks/>
        public string BATHHALF;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPSUBJECTADDR {
        
        /// <remarks/>
        public string STREET;
        
        /// <remarks/>
        public string CITY;
        
        /// <remarks/>
        public string ZIP;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPSUBJECTCONCESSIONS {
        
        /// <remarks/>
        public string SALES;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPS {
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSADDR ADDR;
        
        /// <remarks/>
        public string DATA;
        
        /// <remarks/>
        public string PROXIMITY;
        
        /// <remarks/>
        public string ORIGINALLISTINGDT;
        
        /// <remarks/>
        public string ORIGINALPRICE;
        
        /// <remarks/>
        public string LISTPRICE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSSALE SALE;
        
        /// <remarks/>
        public string SALESPRICE;
        
        /// <remarks/>
        public string MARKETDAYS;
        
        /// <remarks/>
        public string TOTMARKETDAYS;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSSRCFUNDS SRCFUNDS;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSCONCESSIONS CONCESSIONS;
        
        /// <remarks/>
        public string DISTRESSEDSALE;
        
        /// <remarks/>
        public string LOTSIZE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSSITE SITE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSVIEW VIEW;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSVIEWCOMPARISON VIEWCOMPARISON;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSPROPTYPE PROPTYPE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSNUMUNITS NUMUNITS;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSCONSTRUCT CONSTRUCT;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSDESIGNSTYLE DESIGNSTYLE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSAGEYRS AGEYRS;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSCONDITION CONDITION;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSLIVINGSQFT LIVINGSQFT;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSABOVEGRADE ABOVEGRADE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSBASEMENTTYPE BASEMENTTYPE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSBASEMENT BASEMENT;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSBASEMENTFINISH BASEMENTFINISH;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSGARAGE GARAGE;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSPOOL POOL;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSAMENITIES AMENITIES;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSHOAASSESSMENT HOAASSESSMENT;
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSMOSTCOMPARABLE MOSTCOMPARABLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte COMPNUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSADDR {
        
        /// <remarks/>
        public string STREET;
        
        /// <remarks/>
        public string CITY;
        
        /// <remarks/>
        public string ZIP;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSSALE {
        
        /// <remarks/>
        public string DATE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSSRCFUNDS {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSCONCESSIONS {
        
        /// <remarks/>
        public FORMINFOSALESCOMPCOMPSCONCESSIONSSALES SALES;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSCONCESSIONSSALES {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSSITE {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSVIEW {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSVIEWCOMPARISON {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSPROPTYPE {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSNUMUNITS {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSCONSTRUCT {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSDESIGNSTYLE {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSAGEYRS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AGEYRS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSCONDITION {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSLIVINGSQFT {
        
        /// <remarks/>
        public string SQFT;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSABOVEGRADE {
        
        /// <remarks/>
        public string ROOMTOT;
        
        /// <remarks/>
        public string BEDROOMS;
        
        /// <remarks/>
        public string BATHFULL;
        
        /// <remarks/>
        public string BATHHALF;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSBASEMENTTYPE {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSBASEMENT {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSBASEMENTFINISH {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSGARAGE {
        
        /// <remarks/>
        public string DESCRIPTION;
        
        /// <remarks/>
        public string NUMCARS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSPOOL {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSAMENITIES {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSHOAASSESSMENT {
        
        /// <remarks/>
        public string DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOSALESCOMPCOMPSMOSTCOMPARABLE {
        
        /// <remarks/>
        public string RESPONSE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFORECONCIL {
        
        /// <remarks/>
        public FORMINFORECONCILREDFLAG REDFLAG;
        
        /// <remarks/>
        public FORMINFORECONCILESTMARKETVALUE ESTMARKETVALUE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFORECONCILREDFLAG {
        
        /// <remarks/>
        public string DAMAGED;
        
        /// <remarks/>
        public string CONSTRUCTION;
        
        /// <remarks/>
        public string ENVIRONMENTAL;
        
        /// <remarks/>
        public string ZONING;
        
        /// <remarks/>
        public string MARKETACTIVITY;
        
        /// <remarks/>
        public string BOARDED;
        
        /// <remarks/>
        public string STIGMA;
        
        /// <remarks/>
        public string OTHER;
        
        /// <remarks/>
        public string COMMENTS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFORECONCILESTMARKETVALUE {
        
        /// <remarks/>
        public FORMINFORECONCILESTMARKETVALUEQUICKMKTTIME QUICKMKTTIME;
        
        /// <remarks/>
        public FORMINFORECONCILESTMARKETVALUENORMALMKTTIME NORMALMKTTIME;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFORECONCILESTMARKETVALUEQUICKMKTTIME {
        
        /// <remarks/>
        public FORMINFORECONCILESTMARKETVALUEQUICKMKTTIMEASIS ASIS;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFORECONCILESTMARKETVALUEQUICKMKTTIMEASIS {
        
        /// <remarks/>
        public string LISTAMT;
        
        /// <remarks/>
        public string AMT;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFORECONCILESTMARKETVALUENORMALMKTTIME {
        
        /// <remarks/>
        public FORMINFORECONCILESTMARKETVALUENORMALMKTTIMEASIS ASIS;
        
        /// <remarks/>
        public FORMINFORECONCILESTMARKETVALUENORMALMKTTIMEREPAIRED REPAIRED;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFORECONCILESTMARKETVALUENORMALMKTTIMEASIS {
        
        /// <remarks/>
        public string DAYS;
        
        /// <remarks/>
        public string LISTAMT;
        
        /// <remarks/>
        public string AMT;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFORECONCILESTMARKETVALUENORMALMKTTIMEREPAIRED {
        
        /// <remarks/>
        public string DAYS;
        
        /// <remarks/>
        public string LISTAMT;
        
        /// <remarks/>
        public string AMT;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMS {
        
        /// <remarks/>
        public FORMINFOADDENDUMSSIGNATURE SIGNATURE;
        
        /// <remarks/>
        public FORMINFOADDENDUMSSUBJECTPHOTO SUBJECTPHOTO;
        
        /// <remarks/>
        public FORMINFOADDENDUMSADDITIONALPHOTOS ADDITIONALPHOTOS;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("COMPPHOTO")]
        public FORMINFOADDENDUMSCOMPPHOTO[] COMPPHOTO;
        
        /// <remarks/>
        public FORMINFOADDENDUMSLOCATIONMAP LOCATIONMAP;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LISTINGCOMPPHOTO")]
        public FORMINFOADDENDUMSLISTINGCOMPPHOTO[] LISTINGCOMPPHOTO;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSIGNATURE {
        
        /// <remarks/>
        public FORMINFOADDENDUMSSIGNATUREAPPRAISER APPRAISER;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSIGNATUREAPPRAISER {
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSUBJECTPHOTO {
        
        /// <remarks/>
        public FORMINFOADDENDUMSSUBJECTPHOTOFRONTVIEW FRONTVIEW;
        
        /// <remarks/>
        public FORMINFOADDENDUMSSUBJECTPHOTOREARVIEW REARVIEW;
        
        /// <remarks/>
        public FORMINFOADDENDUMSSUBJECTPHOTOSTREETVIEW STREETVIEW;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSUBJECTPHOTOFRONTVIEW {
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DESCRIPTION")]
        public FORMINFOADDENDUMSSUBJECTPHOTOFRONTVIEWDESCRIPTION[] DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSUBJECTPHOTOFRONTVIEWDESCRIPTION {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSUBJECTPHOTOREARVIEW {
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DESCRIPTION")]
        public FORMINFOADDENDUMSSUBJECTPHOTOREARVIEWDESCRIPTION[] DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSUBJECTPHOTOREARVIEWDESCRIPTION {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSUBJECTPHOTOSTREETVIEW {
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DESCRIPTION")]
        public FORMINFOADDENDUMSSUBJECTPHOTOSTREETVIEWDESCRIPTION[] DESCRIPTION;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSSUBJECTPHOTOSTREETVIEWDESCRIPTION {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSADDITIONALPHOTOS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MAP", typeof(FORMINFOADDENDUMSADDITIONALPHOTOSMAP))]
        [System.Xml.Serialization.XmlElementAttribute("PHOTO", typeof(FORMINFOADDENDUMSADDITIONALPHOTOSPHOTO))]
        public object[] Items;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSADDITIONALPHOTOSMAP {
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
        
        /// <remarks/>
        public string TITLE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSADDITIONALPHOTOSPHOTO {
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DESCRIPTION")]
        public FORMINFOADDENDUMSADDITIONALPHOTOSPHOTODESCRIPTION[] DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSADDITIONALPHOTOSPHOTODESCRIPTION {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSCOMPPHOTO {
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte COMPNUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSLOCATIONMAP {
        
        /// <remarks/>
        public string NAME;
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSLISTINGCOMPPHOTO {
        
        /// <remarks/>
        public string FILENAME;
        
        /// <remarks/>
        public string FILETYPE;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DESCRIPTION")]
        public FORMINFOADDENDUMSLISTINGCOMPPHOTODESCRIPTION[] DESCRIPTION;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte COMPNUM;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOADDENDUMSLISTINGCOMPPHOTODESCRIPTION {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte NUM;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOBROKER {
        
        /// <remarks/>
        public string NAME;
        
        /// <remarks/>
        public FORMINFOBROKERLICENSE LICENSE;
        
        /// <remarks/>
        public FORMINFOBROKERCOMPANY COMPANY;
        
        /// <remarks/>
        public string PHONE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOBROKERLICENSE {
        
        /// <remarks/>
        public string NUM;
        
        /// <remarks/>
        public string STATEPROV;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOBROKERCOMPANY {
        
        /// <remarks/>
        public string NAME;
        
        /// <remarks/>
        public string ADDR;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOAPPRAISER {
        
        /// <remarks/>
        public FORMINFOAPPRAISERSIGNED SIGNED;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FORMINFOAPPRAISERSIGNED {
        
        /// <remarks/>
        public string DATE;
    }
}
